name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.68.3
        TARGET_REPO: yoonseo-zoh/yoonseo-zoh.github.io
        TOKEN: ${{ secrets.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 }}
